import '@/app/components/styles/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Sarabun } from 'next/font/google';
import { getServerSession } from 'next-auth';
import SessionProvider from './components/SessionProvider';

config.autoAddCss = false;

const sarabun = Sarabun({
    subsets: ['thai', 'latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

export const metadata = {
    title: 'NextJS Template',
    description: 'Generated by create next app',
};

export default async function Layout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession();
    return (
        <html lang="en">
            <body className={sarabun.className}>
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    );
}
