import { Sarabun } from 'next/font/google';
import { getServerSession } from 'next-auth';

const sarabun = Sarabun({
    subsets: ['thai', 'latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});

export const metadata = {
    title: 'NextJS Template',
    description: 'Generated by create next app',
};

export default async function Layout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession();
    return (
        <html lang="en">
            <body className={sarabun.className}>
                <div>{children}</div>
            </body>
        </html>
    );
}
